name: Generate Code With Chat-GPT

on:
  issues:
    types: [opened, reopened]

jobs:
  access_issue_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set permissions to script.sh
        run: chmod +x scripts/script.sh

      - name: Run the script
        env:
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: ./scripts/script.sh ${GITHUB_TOKEN}, ${REPOSITORY}, ${ISSUE_NUMBER}, ${OPENAI_API_KEY} > ${ISSUE_NUMBER}-response.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: |
            *-response.txt
          if-no-files-found: error

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact
          path: ~/artifact

      - name: List files in the artifact
        run: ls ~/artifact/autocoder-artifact